fix CI
The CI is failing with

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
...
```

when installing packages with pip on new ubuntu versions.
I workaround is to pass the parameter `--break-system-packages` to pip.
A more clean way would be to use python environments, which is not part
of this PR.